### ISSUE TITLE
Nested custom aliases

### ISSUE THREAD

**Issue by Sh4dowsand** [GVigne/TheSleepingLion#2]
**Is your feature request related to a problem? Please describe.**
Nested aliases only work if the contained alias is declared AFTER the containing alias, otherwise a parsing error states that the contained alias can't be found.

**Describe the solution you'd like**
The ideal solution would be to split the custom alias parsing into two stages. First stage just goes over the declaration of names and params of all aliases. As long as they're valid, they get added to the list of 'known aliases'. Once stage 1 is finished for all aliases, the second stage would go through the content of each alias. Since stage 1 has already confirmed the existance of every defined alias, it shouldn't matter what order they're declared in anymore.

**Describe alternatives you've considered**
Alternatively, adding a note to the documentation (and possibly the error message when an alias can't be found) would prevent people from getting confused by this issue.

**Additional context**
Example of the error when the aliases are declared the wrong way round:
![image](https://github.com/GVigne/TheSleepingLion/assets/70750642/78591d49-d120-4b3b-bfeb-2a9deaca10fe)

The same aliases, declared the other way around (with the same card):
![image](https://github.com/GVigne/TheSleepingLion/assets/70750642/a1ba44b3-7098-4be0-bbc5-0c13d83c319f)

**Comment by GVigne** [comment]
Thanks for the examples! 
Even though I hadn't thought of nested aliases, this is not intended and is a bug.
The issue right now is that alias replacement is not recursive, it's only done once and in the order in which you defined the aliases. Here is what is happening in the first case:
- you type`This is a line with \cardtype_config`
- `\config` is not in that line, so nothing happens
- `\cardtype_config`  is in the line and is replaced by `@topleft \config`
Result: `This is a line with @topleft \config`. An error is thrown because `\config` doesn’t exist.

In the second case,
- you type`This is a line with \cardtype_config`
- `\cardtype_config`  is in the line and is replaced by `@topleft \config`. Your instruction is now `This is a line with @topleft \config`
- `\config` in that instruction, so it gets replaced.
Result: `This is a line with @topleft @small Config \image{images\active_config.svg} @end`. No error is thrown.

It's not that The Sleeping Lion doesn't recognize or know aliases, it's just that it doesn't apply them correctly.

Your comment brings up another problem: custom alias messages can be confusing. If you define the alias `\cleanse = \p` then nothing weird happens. However, trying to use that alias will throw the error `The command \p isn't defined`, which is confusing since you only wrote `\cleanse` on the card.

**Comment by GVigne** [comment]
Fixed in 64794b52a49154469d6531498d4032a9be051938. You can now define aliases in any order.
Thanks for your feedback and your patience!
